export enum Games {
  SUDOKU = "sudoku",
  TETRIS = "tetris",
  CONNECT_FOUR = "connect-four",
  CHESS = "chess",
  CHECKERS = "checkers",
  CROSSWORD = "crossword",
  GO = "go",
  GAME_OF_LIFE = "game-of-life",
  PONG = "pong",
  SNAKE = "snake",
  TIC_TAC_TOE = "tic-tac-toe",
  GOMOKU = "gomoku",
  WORDLE = "wordle",
  SCRABBLE = "scrabble",
  SPACE_INVADERS = "space-invaders",
}
