export enum ProjectDialog {
  CREATE_PROJECT = "CREATE_PROJECT",
  EDIT_PROJECT = "EDIT_PROJECT",

  CREATE_TASK = "CREATE_TASK",
  EDIT_TASK = "EDIT_TASK",

  PROJECT_SETTINGS = "PROJECT_SETTINGS",
}
