import type { NewWorkflow, NewWorkflowStatus } from "@wingmnn/db";

export const workflows: Array<NewWorkflow> = [
  {
    id: "basic",
    name: "Basic",
    description: "Simple workflow for basic task management",
    order: ["todo", "in-progress", "done"],
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "kanban",
    name: "Kanban",
    description: "Traditional kanban board workflow",
    order: ["backlog", "ready", "in-progress", "review", "done"],
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "scrum",
    name: "Scrum",
    description: "Agile scrum workflow with testing phase",
    order: ["todo", "in-progress", "review", "testing", "done"],
    createdBy: "system",
    updatedBy: "system",
  },
];

// Status definitions for each workflow
export const workflowStatuses: Record<string, NewWorkflowStatus[]> = {
  basic: [
    {
      id: "todo",
      name: "To Do",
      description: "Tasks that need to be started",
      phase: "backlog",
      color: "#6b7280",
      workflowId: "basic",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "in-progress",
      name: "In Progress",
      description: "Tasks currently being worked on",
      phase: "execution",
      color: "#3b82f6",
      workflowId: "basic",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "done",
      name: "Done",
      description: "Completed tasks",
      phase: "closure",
      color: "#10b981",
      workflowId: "basic",
      createdBy: "system",
      updatedBy: "system",
    },
  ],
  kanban: [
    {
      id: "backlog",
      name: "Backlog",
      description: "Ideas and tasks to be prioritized",
      phase: "backlog",
      color: "#6b7280",
      workflowId: "kanban",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "ready",
      name: "Ready",
      description: "Tasks ready to be worked on",
      phase: "ideation",
      color: "#f59e0b",
      workflowId: "kanban",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "in-progress",
      name: "In Progress",
      description: "Tasks currently being worked on",
      phase: "execution",
      color: "#3b82f6",
      workflowId: "kanban",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "review",
      name: "Review",
      description: "Tasks under review",
      phase: "feedback",
      color: "#8b5cf6",
      workflowId: "kanban",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "done",
      name: "Done",
      description: "Completed tasks",
      phase: "closure",
      color: "#10b981",
      workflowId: "kanban",
      createdBy: "system",
      updatedBy: "system",
    },
  ],
  scrum: [
    {
      id: "todo",
      name: "To Do",
      description: "Tasks in the sprint backlog",
      phase: "backlog",
      color: "#6b7280",
      workflowId: "scrum",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "in-progress",
      name: "In Progress",
      description: "Tasks being worked on in current sprint",
      phase: "execution",
      color: "#3b82f6",
      workflowId: "scrum",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "review",
      name: "Review",
      description: "Tasks ready for code review",
      phase: "feedback",
      color: "#8b5cf6",
      workflowId: "scrum",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "testing",
      name: "Testing",
      description: "Tasks in testing/QA phase",
      phase: "feedback",
      color: "#f59e0b",
      workflowId: "scrum",
      createdBy: "system",
      updatedBy: "system",
    },
    {
      id: "done",
      name: "Done",
      description: "Tasks completed and deployed",
      phase: "closure",
      color: "#10b981",
      workflowId: "scrum",
      createdBy: "system",
      updatedBy: "system",
    },
  ],
};
